### ISSUE TITLE
please release and publish 0.3.0 (or 0.2.1) to sonatype

### ISSUE THREAD

**Issue by jozic** [softprops/retry#18]

**Comment by softprops** [comment]
published and released 0.2.1 and ran the sona type sync process so it should be queued up for maven central resolution soon

the jar should be up on bintray now https://bintray.com/softprops/maven/retry/0.2.1/view#files/me/lessis/retry_2.11/0.2.1

when it does sync up it should show up [here](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22retry_2.11%22)

**Comment by jozic** [comment]
thanks @softprops !
